import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  sidebar: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: -350,
    width: 350,
    backgroundColor: '#333',
    zIndex: 3,
    paddingVertical: 20,
    paddingHorizontal: 15,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 2,
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingBottom: 20,
  },
  scrollView: {
    width: '100%',
    paddingRight: 5,
  },
  manageAccountText: {
    color: '#fff',
    padding: 10,
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  profilePictureContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  profilePicture: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderColor: '#fff',
    borderWidth: 3,
  },
  editButton: {
    position: 'absolute',
    right: 5,
    bottom: 5,
    backgroundColor: 'rgba(0, 0, 0, 1)',
    width: 30,
    height: 30,
    borderRadius: 15,
    padding: 5,
  },
  nameAndBadgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  username: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  badge: {
    width: 25,
    height: 25,
    marginLeft: 5,
  },
  email: {
    color: '#bbb',
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
  },
  linkedAccountsContainer: {
    width: '100%',
    marginTop: 20,
    paddingTop: 10,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    backgroundColor: '#444',
    borderColor: '#444',
    padding: 15,
    borderRadius: 10,
  },
  linkedAccountsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 10,
  },
  linkedAccountsText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  noLinkedAccountsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  noLinkedAccountsText: {
    fontSize: 16,
    color: '#bbb',
    textAlign: 'center',
    marginVertical: 20,
  },
  collapsedAccountsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  collapsedAccountProfilePicture: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderColor: '#fff',
    borderWidth: 2,
    marginRight: 5,
  },
  collapsedAccountText: {
    fontSize: 16,
    color: '#fff',
  },
  accountBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#444',
    padding: 10,
    marginBottom: 10,
    borderRadius: 8,
    width: '100%',
  },
  accountBoxesScrollView: {
    maxHeight: 180,
    marginTop: 10,
  },
  nonScrollableAccountsContainer: {
    marginTop: 10,
  },
  accountProfilePicture: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderColor: '#fff',
    borderWidth: 2,
    marginRight: 10,
  },
  accountInfo: {
    flex: 1,
  },
  accountUsername: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  accountEmail: {
    fontSize: 14,
    color: '#bbb',
  },
  addAccountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#007bff',
    padding: 10,
    borderRadius: 8,
    width: '100%',
    marginTop: 10,
  },
  addAccountText: {
    fontSize: 16,
    color: '#fff',
    marginLeft: 5,
  },
  statsContainer: {
    width: '100%',
    backgroundColor: '#444',
    padding: 15,
    borderRadius: 10,
    marginTop: 20,
    marginBottom: 20,
  },
  statsTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'left',
  },
  statItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  statLabel: {
    color: '#ddd',
    fontSize: 16,
  },
  statValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  reportedPotholesContainer: {
    width: '100%',
    backgroundColor: '#444',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
  },
  reportedPotholesTitle : {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'left',
  },
  potholeScroll: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  potholeCard: {
    width: 200,
    backgroundColor: '#555',
    borderRadius: 10,
    padding: 10,
    marginRight: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  potholeImage: {
    width: '100%',
    height: 80,
    borderRadius: 5,
    marginBottom: 10,
  },
  potholeTimestamp: {
    fontSize: 12,
    color: '#eee',
  },
  potholeStatus: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
  },
  potholeLocation: {
    fontSize: 12,
    color: '#eee',
  },  
  noPotholesText: {
    fontSize: 14,
    color: '#ccc',
    textAlign: 'center',
    marginTop: 20,
  },
  loadingContainer: {
    flex: 1,
    flexDirection: 'row'
  },
  loadingText: {
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    marginLeft: 10
  },
});

export default styles;
