import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

const styles = StyleSheet.create({
 mobileSidebar: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: screenWidth,
    width: '100%',
    height: '100%',
    backgroundColor: '#333',
    zIndex: 4,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 10,
  },
  backButton: {
    position: 'absolute',
    top: 15,
    left: 12,
    zIndex: 5,
    backgroundColor: '#444',
    borderRadius: 20,
    padding: 8,
  },
  contentContainer: {
    width: '80%',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  manageAccountText: {
    color: '#fff',
    padding: 10,
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  profilePictureContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  profilePicture: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderColor: '#fff',
    borderWidth: 2,
  },
  editButton: {
    position: 'absolute',
    right: 5,
    bottom: 5,
    backgroundColor: 'rgba(0, 0, 0, 1)',
    width: 30,
    height: 30,
    borderRadius: 15,
    padding: 5,
  },
  username: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  email: {
    color: '#bbb',
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
  },
  linkedAccountsContainer: {
    width: '100%',
    marginTop: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#444',
  },
  linkedAccountsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 10,
  },
  linkedAccountsText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  collapsedAccountsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  collapsedAccountProfilePicture: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderColor: '#fff',
    borderWidth: 2,
    marginRight: 5,
  },
  collapsedAccountText: {
    fontSize: 16,
    color: '#fff',
  },
  accountBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#444',
    padding: 10,
    marginBottom: 10,
    borderRadius: 8,
    width: '100%',
  },
  accountBoxesScrollView: {
    maxHeight: 180,
    marginTop: 10,
  },
  accountProfilePicture: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderColor: '#fff',
    borderWidth: 2,
    marginRight: 10,
  },
  accountInfo: {
    flex: 1,
  },
  accountUsername: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  accountEmail: {
    fontSize: 14,
    color: '#bbb',
  },
  addAccountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#007bff',
    padding: 10,
    borderRadius: 8,
    width: '100%',
    marginTop: 10,
  },
  addAccountText: {
    fontSize: 16,
    color: '#fff',
    marginLeft: 5,
  },
});

export default styles;
