import React, { useState, useEffect, useRef } from 'react';
import { View, Text, Pressable, Alert, Animated, Easing } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';
import styles from '../home-page/home.style';
import { useNavigation } from '@react-navigation/native';
import { auth } from '../../config/firebase/firebase-config';

const HomePage = ({ route }) => {
  const { user } = route.params;
  const [sidebarVisible, setSidebarVisible] = useState(false);
  const navigation = useNavigation();
  const sidebarAnim = useRef(new Animated.Value(-250)).current;

  // sets a menu icon in the appbar generated by useNavigation() and slide the appbar title to the right a bit
  useEffect(() => {
    navigation.setOptions({
      headerLeft: () => (
        <Pressable onPress={toggleSidebar} style={{ paddingLeft: 20 }}>
          <Icon name="menu" size={24} color="#fff" />
        </Pressable>
      ),
      headerTitle: () => (
        <View style={{ flexDirection: 'row', alignItems: 'center' }}>
          <Text style={{ color: '#fff', fontSize: 20, marginLeft: 20 }}>RoadGuard</Text>
        </View>
      ),
      headerStyle: {
        backgroundColor: 'blue',
      },
      headerTintColor: '#fff',
      headerTitleStyle: {
        fontWeight: 'bold',
      },
    });
  }, [navigation, sidebarVisible]);

  // redirect a user to the home page if they are not authenticated
  useEffect(() => {
    if (!auth.currentUser) {
      navigation.reset({
        index: 0,
        routes: [{ name: 'Welcome' }],
      });
    }
  }, [auth.currentUser, navigation]);

  const handleLogout = async () => {
    console.log('Logging out...');
    await auth.signOut();
    console.log('User signed out, navigating to Welcome...');
    navigation.reset({
      index: 0,
      routes: [{ name: 'Welcome' }],
    });
  };

  if (!user) {
    return (
      <View style={styles.container}>
        <Text>Loading...</Text>
      </View>
    );
  }

  const toggleSidebar = () => {
    Animated.timing(sidebarAnim, {
      toValue: sidebarVisible ? -250 : 0,
      duration: 300,
      easing: Easing.inOut(Easing.ease),
      useNativeDriver: false,
    }).start();
    setSidebarVisible(!sidebarVisible);
  };

  const handleMenuItemPress = (item) => {
    switch (item) {
      case 'Settings':
        Alert.alert('Settings clicked');
        break;
      case 'Change Password':
        Alert.alert('Change Password clicked');
        break;
      case 'Change Username':
        Alert.alert('Change Username clicked');
        break;
      case 'Delete Account':
        Alert.alert('Delete Account clicked');
        break;
      case 'Logout':
        handleLogout();
        break;
      default:
        break;
    }
  };

  return (
    <View style={styles.container}>
      {sidebarVisible && (
        <Pressable style={styles.overlay} onPress={toggleSidebar}>
        <View style={styles.sidebar}>
          {['Settings', 'Change Password', 'Change Username', 'Delete Account', 'Logout'].map((item) => (
            <Pressable key={item} onPress={() => handleMenuItemPress(item)}>
              <Text style={styles.menuItem}>{item}</Text>
            </Pressable>
          ))}
        </View>
        </Pressable>
      )}
      <View style={[styles.content, sidebarVisible && styles.contentShift]}>
        <Text style={styles.welcomeText}>Welcome to the Home Page, {user.username}!</Text>
      </View>
    </View>
  );
};


export default HomePage;
