import React, { useState, useEffect, useRef } from 'react';
import { View, Text, Pressable, Alert, Animated, Easing } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';
import styles from './home.style';
import { useNavigation } from '@react-navigation/native';
import { auth, db } from '../../../config/firebase/firebase-config';
import { onAuthStateChanged } from 'firebase/auth';
import { updateDoc, doc, setDoc, getDoc } from 'firebase/firestore';
import CitySelection from '../city-selection/city';

const HomePage = () => {
  const navigation = useNavigation();
  const [sidebarVisible, setSidebarVisible] = useState(false);
  const [favoriteCity, setFavoriteCity] = useState('');
  const [user, setUser] = useState(null);
  const [userData, setUserData] = useState({});
  const sidebarAnim = useRef(new Animated.Value(-250)).current;

  // sets a menu icon in the appbar generated by useNavigation() and slide the appbar title to the right a bit
  useEffect(() => {
    navigation.setOptions({
      headerLeft: () => (
        <Pressable onPress={toggleSidebar} style={{ paddingLeft: 20 }}>
          <Icon name="menu" size={24} color="#fff" />
        </Pressable>
      ),
      headerTitle: () => (
        <View style={{ flexDirection: 'row', alignItems: 'center' }}>
          <Text style={{ color: '#fff', fontSize: 20, marginLeft: 20 }}>RoadGuard</Text>
        </View>
      ),
      headerStyle: {
        backgroundColor: 'blue',
      },
      headerTintColor: '#fff',
      headerTitleStyle: {
        fontWeight: 'bold',
      },
    });
  }, [navigation, sidebarVisible]);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      if (currentUser) {
        setUser(currentUser);
        fetchUserData(currentUser.uid);
      } else {
        setUser(null);
        navigation.reset({
          index: 0,
          routes: [{ name: 'Welcome' }],
        });
      }
    });

    return () => unsubscribe();
  }, [navigation]);

  const fetchUserData = async (uid) => {
    try {
      const userDocRef = doc(db, 'users', uid);
      const userDoc = await getDoc(userDocRef);
      if (userDoc.exists()) {
        const userData = userDoc.data();
        setUserData(userData);
        setFavoriteCity(userData.favoriteCity || '');
      } else {
        console.log('No such document!');
      }
    } catch (error) {
      console.error('Error fetching user data:', error);
    }
  };

  const toggleSidebar = () => {
    Animated.timing(sidebarAnim, {
      toValue: sidebarVisible ? -250 : 0,
      duration: 300,
      easing: Easing.inOut(Easing.ease),
      useNativeDriver: false,
    }).start();
    setSidebarVisible(!sidebarVisible);
  };

  const handleLogout = async () => {
    console.log('Logging out...');
    await auth.signOut();
    console.log('User signed out, navigating to Welcome...');
    navigation.reset({
      index: 0,
      routes: [{ name: 'Welcome' }],
    });
  };

  const handleCitySelect = async (city) => {
    console.log("handleCitySelect called");
    setFavoriteCity(city);
  
    if (user) {
      console.log("User object:", user);
      console.log("User UID:", user.uid);
      console.log("Selected City:", city);
  
      const userDocRef = doc(db, 'users', user.uid);
      try {
        await setDoc(userDocRef, { favoriteCity: city }, { merge: true });
        console.log(`Favorite city for ${user.uid} set to ${city}`);
      } catch (error) {
        console.error("Error updating favorite city:", error);
      }
    } else {
      console.error("User is undefined. Cannot update favorite city.");
    }
  };

  const handleMenuItemPress = (item) => {
    switch (item) {
      case 'Settings':
        Alert.alert('Settings clicked');
        break;
      case 'Change Password':
        Alert.alert('Change Password clicked');
        break;
      case 'Change Username':
        Alert.alert('Change Username clicked');
        break;
      case 'Delete Account':
        Alert.alert('Delete Account clicked');
        break;
      case 'Logout':
        handleLogout();
        break;
      default:
        break;
    }
  };

  if (!user) {
    return (
      <View style={styles.container}>
        <Text>Loading...</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      {sidebarVisible && (
        <Pressable style={styles.overlay} onPress={toggleSidebar}>
        <View style={styles.sidebar}>
          {['Settings', 'Change Password', 'Change Username', 'Delete Account', 'Logout'].map((item) => (
            <Pressable key={item} onPress={() => handleMenuItemPress(item)}>
              <Text style={styles.menuItem}>{item}</Text>
            </Pressable>
          ))}
        </View>
        </Pressable>
      )}
      <View style={[styles.content, sidebarVisible && styles.contentShift]}>
        <Text style={styles.welcomeText}>Welcome to the Home Page, {userData.username}!</Text>
        <CitySelection onCitySelect={handleCitySelect} />
        <Text>Your favorite city is: {favoriteCity}</Text>
      </View>
    </View>
  );
};

export default HomePage;
